# paths (need if not get latest)
video_tokenizer_path: /localhome/local-triv/tinyworlds/results/2026_06_08_12_51_05_zelda/video_tokenizer/checkpoints/video_tokenizer_step_37500
latent_actions_path: /localhome/local-triv/tinyworlds/results/2026_06_08_12_51_05_zelda/latent_actions/checkpoints/latent_actions_step_9500
dynamics_path: /localhome/local-triv/tinyworlds/results/2026_06_22_04_33_07/dynamics/checkpoints/dynamics_step_11500
use_latest_checkpoints: false

# inference params
dataset: ZELDA
preload_ratio:
device: cuda # make sure to use correct device
generation_steps: 5
context_window: 4  # 2
fps: 2
temperature: 0.5 # 0 is argmax
teacher_forced: true # for testing/dev
prediction_horizon: 1 # how many masked frames to append and decode at a time

# action selection modes (lower takes priority)
use_actions: false # use random actions
use_gt_actions: true #false # use lam-inferred actions
use_interactive_mode: false # true # use user-inputted actions

# inference acceleration
amp: false
tf32: false
compile: false